status = [
  "buildkite/rvl-test",
#  "continuous-integration/appveyor/branch",
#  "ci/hydra:serokell:cardano-sl:all-cardano-sl.x86_64-linux"
]
timeout_sec = 7200
required_approvals = 1
cut_body_after = "## Type of change"
delete_merged_branches = true
block_labels = [ "DO NOT MERGE", "wip" ]
