steps:
  - label: 'hello'
    command:
      - 'nix-shell -p cowsay --run "cowsay a little bit better"'
      - "sleep 60"
    agents:
      system: x86_64-linux
  - label: 'think'
    command:
      - 'nix-shell -p cowsay --run "cowthink im bored"'
      - "sleep 10"
    agents:
      system: x86_64-linux
 
  - label: 'bomb'
    command: "false"
    agents:
      system: x86_64-linux
