steps:
  - label: '5 second test'
    command:
      - 'sleep 5'
      - 'echo :success:'
    agents:
      system: x86_64-linux

  - label: 'hello'
    command: 'nix-shell -p cowsay --run "cowsay hello"'
    agents:
      system: x86_64-linux
