steps:
  - label: '10 second test'
    command:
      - 'sleep 10'
      - 'echo :success:'
    agents:
      system: x86_64-linux

  - label: 'more testing'
    command: 'nix-shell -p cowsay --run "cowsay bors-ng"'
    agents:
      system: x86_64-linux
