steps:
  - label: 'hello'
    command: 'nix-shell -p cowsay --run "cowsay this is pr #11"'
    agents:
      system: x86_64-linux
  - label: 'think'
    command:
      - 'nix-shell -p cowsay --run "cowthink im bored"'
      - "sleep 10"
    agents:
      system: x86_64-linux
