steps:
  - label: '10 second test'
    command:
      - 'sleep 10'
      - 'echo :success:'
    agents:
      system: x86_64-linux

  - label: 'hello'
    command: 'nix-shell -p cowsay --run "cowsay hello"'
    agents:
      system: x86_64-linux
 
  - label: 'bomb'
    command: "false"
    agents:
      system: x86_64-linux
